print("Welcone to your adventure simulator. I am going to ask you a bunch of questions and then create an epci story with you as the star!! Lets play!")
print()
print("What is your name?")
name = input()
print()
print("What is your age?")
age = input()
print()
print("What is your favorite color?")
color = input()
print()
print("What is your favorite food?")
food = input()
print()
print("What is your favorite animal?")
animal = input()
print()
print("What is your favorite sport?")
sport = input()
print()
print("What is your favorite hobby?")
hobby = input()
print()
print("What is your favorite music genre?")
music = input()
print()
print("What is your favorite book?")
book = input()
print()
print("What is your favorite movie?")
movie = input()
print()
print("Hello\033[31m",name, "\033[0m! At this age of\033[32m",age, "\033[0m, you like to get dressed in\033[33m",color, "\033[0mand enjoy eating\033[34m",food, "\033[0m. Playing\033[35m",sport, "\033[0mand \033[35m",hobby, "\033[0mare your favorite things to do, apart from listening to\033[36m",music, "\033[0mand reading\033[36m",book, "\033[0m. You also like watching\033[35m",movie, "\033[0m.")
print()
print("Thank you for playing my adventure simulator. Have a nice day!")