print("Gourmet recipe!")
print()
food = input("What food do you want to cook? ")
plant = input("What plant do you want to cook? ")
method = input("How do you want to cook it? ")
burnt = input("A word to describe burned food? ")
household = input("Name a household item: ")
print("Here is your recipe:")
print(method, food, "with", burnt, plant, "on a bed of", household)