print("Getting to know you!")
myName = input ("Your name: ")
myFavFood = input ("Your favorite food: ")
myFavMusic = input ("Your favorite music: ")
myPlace = input ("Where do you live? ")
print ("You are ")
print (myName)
print ("You are probably hungry for")
print (myFavFood)
print ("and you're definitely getting your groove")
print ("on to", myFavMusic)
print ("living in the amazing", myPlace)
print ("Have a great day!")